// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPIEF;

#nullable disable

namespace PokemonAPIEF.Migrations
{
    [DbContext(typeof(PokemonAPIEFContext))]
    [Migration("20250310222724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PokemonAPIEF.Models.CachedPokemonSpecies", b =>
                {
                    b.Property<string>("SpeciesName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitatName")
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsLegendary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCached")
                        .HasColumnType("datetime");

                    b.Property<string>("TranslatedDescription")
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.HasKey("SpeciesName");

                    b.ToTable("CachedPokemonSpecies");
                });
#pragma warning restore 612, 618
        }
    }
}
